name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          docker pull honeygain/honeygain
          docker run honeygain/honeygain -tou-accept -email ${{ secrets.EMAIL }} -pass ${{ secrets.PASSWD }} -device github-actions
