name: CI
on:
  push:
    branches: *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          docker pull honeygain/honeygain
          docker run honeygain/honeygain -tou-accept -email gilmarsilva1@gmail.com -pass rm310422 -device docker-mac
